Server Port: 57719
OpenAPI Only If not Localhost: true
System Codes:
  'BSL|AdminPermissi0n992719':
    Name: 'Admin'
    Permission:
      - ADMIN
  'BSL|ModeratorPermission299945':
    Name: 'Moderator'
    Permission:
      - RESOURCE_SET
      - RESOURCE_GET
      - OPEN_API
  'BSL|DataIdentifier00':
    Name: 'Info'
    Permission:
      - RESOURCE_GET
      - OPEN_API