# Bukkit connection validate code.
# Please change after use.
# WARNING: Bukkit and bungeecord's System identify code must have to equal.
System Identify Code: 'BSL|DataIdentifier00'
# Server name.
System Name: 'Client Server'
# Bungeecord IP / port.
# BungeeSwitchListener connection with fake player connection to communicate.
Bungeecord IP: 'localhost'
Bungeecord Port: 57719